/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as OfertaRouteImport } from './routes/oferta'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as UpsellRouteImport } from './routes/upsell'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaRoute = OfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const UpsellRoute = UpsellRouteImport.update({
  id: '/upsell',
  path: '/upsell',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/comunidade': typeof ComunidadeRoute
  '/download': typeof DownloadRoute
  '/oferta': typeof OfertaRoute
  '/pagamento': typeof PagamentoRoute
  '/prompts': typeof PromptsRoute
  '/upsell': typeof UpsellRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/comunidade': typeof ComunidadeRoute
  '/download': typeof DownloadRoute
  '/oferta': typeof OfertaRoute
  '/pagamento': typeof PagamentoRoute
  '/prompts': typeof PromptsRoute
  '/upsell': typeof UpsellRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/comunidade': typeof ComunidadeRoute
  '/download': typeof DownloadRoute
  '/oferta': typeof OfertaRoute
  '/pagamento': typeof PagamentoRoute
  '/prompts': typeof PromptsRoute
  '/upsell': typeof UpsellRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/comunidade'
    | '/download'
    | '/oferta'
    | '/pagamento'
    | '/prompts'
    | '/upsell'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/comunidade'
    | '/download'
    | '/oferta'
    | '/pagamento'
    | '/prompts'
    | '/upsell'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/comunidade'
    | '/download'
    | '/oferta'
    | '/pagamento'
    | '/prompts'
    | '/upsell'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  ComunidadeRoute: typeof ComunidadeRoute
  DownloadRoute: typeof DownloadRoute
  OfertaRoute: typeof OfertaRoute
  PagamentoRoute: typeof PagamentoRoute
  PromptsRoute: typeof PromptsRoute
  UpsellRoute: typeof UpsellRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta': {
      id: '/oferta'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof OfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell': {
      id: '/upsell'
      path: '/upsell'
      fullPath: '/upsell'
      preLoaderRoute: typeof UpsellRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  ComunidadeRoute: ComunidadeRoute,
  DownloadRoute: DownloadRoute,
  OfertaRoute: OfertaRoute,
  PagamentoRoute: PagamentoRoute,
  PromptsRoute: PromptsRoute,
  UpsellRoute: UpsellRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
